export const routes = {
  login: '/accounts/login/',
  userInfo: '/accounts/users/me/',
  logout: '/accounts/logout/',
  companiesList: '/companies/',
  company: (companyId) => `/companies/${companyId}/`,
  companySimulations: (companyId) => `/companies/${companyId}/simulations/`,
  companySimulation: (companyId, simulationId) => `/companies/${companyId}/simulations/${simulationId}/`,
  companyDetailedSimulations: (companyId) => `/companies/${companyId}/detailed-simulations/`,
  expenses: '/expenses/',
  expense: (expenseId) => `/expenses/${expenseId}/`,
  linkExpense: (companyId, simulationId) => `/companies/${companyId}/simulations/${simulationId}/link_expense/`,
  unlinkExpense: (companyId, simulationId) => `/companies/${companyId}/simulations/${simulationId}/unlink_expense/`,
  linkExpenses: (companyId, simulationId) => `/companies/${companyId}/simulations/${simulationId}/link_expenses/`,
  unlinkExpenses: (companyId, simulationId) => `/companies/${companyId}/simulations/${simulationId}/unlink_expenses/`,
  transactions: (companyId) => `/companies/${companyId}/transactions/`,
  transaction: (companyId, transactionId) => `/companies/${companyId}/transactions/${transactionId}/`,
  yearTransactions: (companyId, year = null, page=1) => `/companies/${companyId}/transactions/?year=${year}&page=${page}`,
  feedback: '/feedback/',
  summary: (companyId, year) => `/companies/${companyId}/summary/?year=${year}`,
}
